import React, { useEffect, useState } from 'react';

interface Goal {
  id: number;
  name: string;
  description: string;
  current: number;
  target: number;
  color: string;
  icon: string;
  targetDate?: string;
  subGoals?: string[];
  completedSubGoals?: number[];
  isPrimary?: boolean;
}

const SUB_GOALS_DATA = {
  'Emergency Fund': [
    '💳 Pay off credit card debt',
    '📱 Cancel unused subscriptions',
    '🍽️ Cook meals at home more often',
    '☕ Reduce coffee shop visits',
    '🎬 Use free entertainment options'
  ],
  'Vacation Fund': [
    '✈️ Book flights early for discounts',
    '🏨 Research budget accommodations',
    '🍕 Set aside money weekly for trip',
    '💼 Pick up extra work/shifts',
    '🛍️ Avoid impulse purchases this month'
  ],
  'Home Down Payment': [
    '🏠 Research first-time buyer programs',
    '💰 Open a high-yield savings account',
    '📊 Track all expenses for 3 months',
    '🎯 Set monthly savings target',
    '📚 Learn about mortgage pre-approval'
  ],
  'Car Fund': [
    '🚗 Research car models and prices',
    '💵 Save on gas by combining trips',
    '🔧 Maintain current car to avoid repairs',
    '🚌 Use public transport when possible',
    '💡 Compare insurance rates'
  ],
  'Education Fund': [
    '📚 Apply for scholarships and grants',
    '💻 Look for online course discounts',
    '📖 Buy used textbooks',
    '👥 Form study groups to share costs',
    '🎓 Research tuition payment plans'
  ],
  'Retirement': [
    '📈 Maximize employer 401k match',
    '💰 Open an IRA account',
    '📊 Review investment allocations',
    '💡 Reduce unnecessary expenses',
    '📚 Educate yourself on investing'
  ],
  'General': [
    '💰 Track daily expenses',
    '🎯 Set weekly savings goals',
    '🛍️ Wait 24hrs before big purchases',
    '📱 Use budgeting apps',
    '💡 Find ways to increase income'
  ]
};

const generateSubGoalsForGoal = (goalName: string): string[] => {
  const nameLower = goalName.toLowerCase();
  if (nameLower.includes('emergency')) return SUB_GOALS_DATA['Emergency Fund'];
  if (nameLower.includes('vacation') || nameLower.includes('travel') || nameLower.includes('trip')) return SUB_GOALS_DATA['Vacation Fund'];
  if (nameLower.includes('home') || nameLower.includes('house') || nameLower.includes('down payment')) return SUB_GOALS_DATA['Home Down Payment'];
  if (nameLower.includes('car') || nameLower.includes('vehicle') || nameLower.includes('auto')) return SUB_GOALS_DATA['Car Fund'];
  if (nameLower.includes('education') || nameLower.includes('school') || nameLower.includes('college') || nameLower.includes('university')) return SUB_GOALS_DATA['Education Fund'];
  if (nameLower.includes('retirement') || nameLower.includes('pension') || nameLower.includes('401k')) return SUB_GOALS_DATA['Retirement'];
  return SUB_GOALS_DATA['General'];
};

declare global {
  var goalsState: Goal[];
  var setGoalsState: React.Dispatch<React.SetStateAction<Goal[]>>;
  var addNewGoal: ((goal: Goal) => void) | undefined;
  var updateGoal: ((goal: Goal) => void) | undefined;
  var getPrimaryGoal: (() => Goal | undefined) | undefined;
}

export function GoalsProvider({ children }: { children: React.ReactNode }) {
  const [goals, setGoals] = useState<Goal[]>([
    {
      id: 1,
      name: 'Emergency Fund',
      description: 'Save for emergencies',
      current: 1500,
      target: 5000,
      color: '#3B82F6',
      icon: '🛡️',
      subGoals: SUB_GOALS_DATA['Emergency Fund'],
      completedSubGoals: [],
      isPrimary: true,
    },
    {
      id: 2,
      name: 'Vacation Fund',
      description: 'Summer trip 2025',
      current: 800,
      target: 3000,
      color: '#10B981',
      icon: '✈️',
      subGoals: SUB_GOALS_DATA['Vacation Fund'],
      completedSubGoals: [],
      isPrimary: false,
    },
  ]);

  useEffect(() => {
    // Make goals accessible globally
    global.goalsState = goals;
    global.setGoalsState = setGoals;

    global.addNewGoal = (newGoal: Goal) => {
      const autoGeneratedSubGoals = generateSubGoalsForGoal(newGoal.name);
      const goalWithSubGoals = {
        ...newGoal,
        subGoals: autoGeneratedSubGoals,
        isPrimary: false
      };
      
      setGoals(prevGoals => [...prevGoals, goalWithSubGoals]);
    };

    global.updateGoal = (updatedGoal: Goal) => {
      setGoals(prevGoals => 
        prevGoals.map(goal => 
          goal.id === updatedGoal.id ? updatedGoal : goal
        )
      );
    };

    global.getPrimaryGoal = () => {
      return goals.find(goal => goal.isPrimary);
    };

    return () => {
      delete global.addNewGoal;
      delete global.updateGoal;
      delete global.getPrimaryGoal;
    };
  }, [goals]);

  return <>{children}</>;
}